/**
 * AdminTrainingPlans — /admin/training-plans
 * Lists all survey groups with their AI-generated training plan status.
 * HR Officers can:
 *  - Generate a training plan (calls groups.generateSection with sectionKey="training_plan")
 *  - Re-generate to refresh the plan
 *  - Download the plan as a Markdown (.md) file
 *  - View the full plan inline in an expandable card
 */
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";
import {
  GraduationCap, Loader2, Download, RefreshCw, ChevronDown, ChevronUp,
  Tag, AlertCircle, CheckCircle2, Clock, Sparkles, FileText, Users,
} from "lucide-react";
import { cn } from "@/lib/utils";

type Group = {
  id: number;
  name: string;
  code: string;
  description: string | null;
  sectorId: number | null;
  isActive: boolean;
  expectedCount: number | null;
};

type Section = {
  id: number;
  groupId: number;
  sectionKey: string;
  sectionTitle: string;
  content: string;
  updatedAt: Date;
};

// ─── Markdown downloader ──────────────────────────────────────────────────────
function downloadMarkdown(groupName: string, groupCode: string, content: string) {
  const filename = `Training-Plan-${groupCode}-${new Date().toISOString().slice(0, 10)}.md`;
  const header = `# Training Plan — ${groupName}\n\n> Generated by TNA System on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}\n\n---\n\n`;
  const blob = new Blob([header + content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
  toast.success(`Training plan downloaded as ${filename}`);
}

// ─── Single Group Training Plan Card ─────────────────────────────────────────
function GroupPlanCard({ group, sectors }: { group: Group; sectors: { id: number; name: string }[] }) {
  const [expanded, setExpanded] = useState(false);
  const utils = trpc.useUtils();

  const { data: sections, isLoading: sectionsLoading } = trpc.groups.getAnalysisSections.useQuery(
    { groupId: group.id },
    { refetchOnWindowFocus: false }
  );

  const trainingPlanSection = sections?.find((s: Section) => s.sectionKey === "training_plan");

  const generate = trpc.groups.generateSection.useMutation({
    onSuccess: (result) => {
      toast.success(result.fromCache ? "Training plan loaded from cache." : "Training plan generated successfully!");
      utils.groups.getAnalysisSections.invalidate({ groupId: group.id });
    },
    onError: (e) => {
      if (e.message.includes("No survey responses")) {
        toast.error("No survey responses found for this group. Collect responses before generating a plan.");
      } else {
        toast.error(e.message || "Failed to generate training plan.");
      }
    },
  });

  const isGenerating = generate.isPending;
  const hasPlan = !!trainingPlanSection;
  const sector = sectors.find((s) => s.id === group.sectorId);

  const handleGenerate = (forceRegenerate = false) => {
    generate.mutate({
      groupId: group.id,
      sectionKey: "training_plan",
      forceRegenerate,
    });
  };

  return (
    <Card className={cn("transition-shadow", hasPlan ? "hover:shadow-md" : "border-dashed")}>
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-3">
          {/* Left: Group info */}
          <div className="flex items-start gap-3 min-w-0">
            <div className={cn(
              "w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0",
              hasPlan ? "bg-emerald-100" : "bg-slate-100"
            )}>
              {hasPlan
                ? <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                : <FileText className="w-5 h-5 text-slate-400" />
              }
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <CardTitle className="text-base font-semibold text-slate-900 truncate">{group.name}</CardTitle>
                <Badge variant="outline" className="font-mono text-xs flex-shrink-0">{group.code}</Badge>
                {!group.isActive && (
                  <Badge variant="secondary" className="text-xs flex-shrink-0">Inactive</Badge>
                )}
              </div>
              <div className="flex items-center gap-3 mt-1 flex-wrap">
                {sector && (
                  <span className="text-xs text-slate-500 flex items-center gap-1">
                    <Tag className="w-3 h-3" />
                    {sector.name}
                  </span>
                )}
                {group.expectedCount && group.expectedCount > 0 && (
                  <span className="text-xs text-slate-500 flex items-center gap-1">
                    <Users className="w-3 h-3" />
                    {group.expectedCount} expected
                  </span>
                )}
                {hasPlan && trainingPlanSection && (
                  <span className="text-xs text-slate-400 flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    Updated {new Date(trainingPlanSection.updatedAt).toLocaleDateString()}
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Right: Actions */}
          <div className="flex items-center gap-2 flex-shrink-0">
            {sectionsLoading ? (
              <Loader2 className="w-4 h-4 animate-spin text-slate-400" />
            ) : hasPlan ? (
              <>
                <Button
                  size="sm"
                  variant="outline"
                  className="gap-1.5 text-xs h-8"
                  onClick={() => downloadMarkdown(group.name, group.code, trainingPlanSection!.content)}
                >
                  <Download className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Download</span>
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="gap-1.5 text-xs h-8"
                  onClick={() => handleGenerate(true)}
                  disabled={isGenerating}
                >
                  {isGenerating
                    ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    : <RefreshCw className="w-3.5 h-3.5" />
                  }
                  <span className="hidden sm:inline">{isGenerating ? "Regenerating…" : "Regenerate"}</span>
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  className="h-8 w-8 p-0"
                  onClick={() => setExpanded((v) => !v)}
                  title={expanded ? "Collapse" : "Expand plan"}
                >
                  {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                </Button>
              </>
            ) : (
              <Button
                size="sm"
                className="gap-1.5 text-xs h-8 bg-primary"
                onClick={() => handleGenerate(false)}
                disabled={isGenerating}
              >
                {isGenerating
                  ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  : <Sparkles className="w-3.5 h-3.5" />
                }
                {isGenerating ? "Generating…" : "Generate Plan"}
              </Button>
            )}
          </div>
        </div>
      </CardHeader>

      {/* Inline plan content (expandable) */}
      {hasPlan && expanded && trainingPlanSection && (
        <CardContent className="pt-0">
          <div className="border-t border-slate-100 pt-4">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-slate-700">{trainingPlanSection.sectionTitle}</h3>
              <Button
                size="sm"
                variant="outline"
                className="gap-1.5 text-xs h-7"
                onClick={() => downloadMarkdown(group.name, group.code, trainingPlanSection.content)}
              >
                <Download className="w-3 h-3" />
                Download .md
              </Button>
            </div>
            <div className="bg-slate-50 rounded-lg border border-slate-200 p-4 max-h-96 overflow-y-auto">
              <pre className="text-xs text-slate-700 whitespace-pre-wrap font-mono leading-relaxed">
                {trainingPlanSection.content}
              </pre>
            </div>
          </div>
        </CardContent>
      )}

      {/* Generating skeleton */}
      {isGenerating && (
        <CardContent className="pt-0">
          <div className="border-t border-slate-100 pt-4 space-y-2">
            <div className="flex items-center gap-2 text-sm text-primary">
              <Loader2 className="w-4 h-4 animate-spin" />
              <span>AI is generating the training plan for <strong>{group.name}</strong>…</span>
            </div>
            <p className="text-xs text-slate-400">This may take 15–30 seconds. The plan will appear here when ready.</p>
            <div className="space-y-1.5 mt-2">
              {[80, 60, 70, 50].map((w, i) => (
                <div key={i} className={`h-3 bg-slate-100 rounded animate-pulse`} style={{ width: `${w}%` }} />
              ))}
            </div>
          </div>
        </CardContent>
      )}
    </Card>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function AdminTrainingPlans() {
  const [filter, setFilter] = useState<"all" | "generated" | "pending">("all");
  const [search, setSearch] = useState("");

  const { data: groups, isLoading: groupsLoading } = trpc.groups.list.useQuery(
    { activeOnly: false },
    { refetchOnWindowFocus: false }
  );
  const { data: sectors } = trpc.sectors.list.useQuery({ activeOnly: false });

  // For the filter badges, we need to know which groups have training plans
  // We'll use a separate query for all sections and derive plan status
  const allGroups = groups ?? [];
  const filteredGroups = allGroups.filter((g) => {
    const matchesSearch = !search
      || g.name.toLowerCase().includes(search.toLowerCase())
      || g.code.toLowerCase().includes(search.toLowerCase());
    return matchesSearch;
  });

  const activeGroups = filteredGroups.filter((g) => g.isActive);
  const inactiveGroups = filteredGroups.filter((g) => !g.isActive);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <GraduationCap className="w-6 h-6 text-primary" />
            Training Plans
          </h1>
          <p className="text-slate-500 text-sm mt-1">
            Generate AI-powered training plans for each survey group based on their TNA results.
            Plans are exported as Markdown documents ready for HR use.
          </p>
        </div>
      </div>

      {/* Info Banner */}
      <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
        <div className="flex gap-3">
          <Sparkles className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-blue-800">
            <p className="font-semibold mb-1">How Training Plans Work</p>
            <p>
              Click <strong>Generate Plan</strong> on any group that has collected survey responses.
              The AI analyses the group's competency gaps, score distribution, and sector context to produce
              a structured training plan covering objectives, recommended courses, delivery modes, timeline,
              and budget estimates. Plans can be regenerated at any time and downloaded as Markdown files.
            </p>
          </div>
        </div>
      </div>

      {/* Search */}
      <div className="relative max-w-sm">
        <FileText className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
        <input
          type="text"
          placeholder="Search groups…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="w-full pl-9 pr-4 py-2 text-sm border border-slate-200 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary"
        />
      </div>

      {/* Groups list */}
      {groupsLoading ? (
        <div className="space-y-3">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="h-24 rounded-xl bg-muted animate-pulse" />
          ))}
        </div>
      ) : allGroups.length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center">
            <GraduationCap className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
            <p className="font-semibold text-foreground">No survey groups found</p>
            <p className="text-sm text-muted-foreground mt-1">
              Create survey groups first, then collect responses before generating training plans.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6">
          {/* Active groups */}
          {activeGroups.length > 0 && (
            <div>
              <h2 className="font-semibold text-slate-700 mb-3 text-sm">
                Active Groups ({activeGroups.length})
              </h2>
              <div className="space-y-3">
                {activeGroups.map((group) => (
                  <GroupPlanCard
                    key={group.id}
                    group={group as Group}
                    sectors={sectors ?? []}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Inactive groups */}
          {inactiveGroups.length > 0 && (
            <div>
              <h2 className="font-semibold text-muted-foreground mb-3 text-sm">
                Inactive Groups ({inactiveGroups.length})
              </h2>
              <div className="space-y-3 opacity-70">
                {inactiveGroups.map((group) => (
                  <GroupPlanCard
                    key={group.id}
                    group={group as Group}
                    sectors={sectors ?? []}
                  />
                ))}
              </div>
            </div>
          )}

          {/* No results */}
          {filteredGroups.length === 0 && (
            <div className="text-center py-12">
              <AlertCircle className="w-8 h-8 text-muted-foreground mx-auto mb-2" />
              <p className="text-sm text-muted-foreground">No groups match your search.</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
